#include "adapters/glsl.h"
#include "b.h"

;;DEFINITION
/* GLSL compilation defaults to shaderc's glslc, targeting Vulkan SPIR-V;
 * GLSL_BACKEND=glslang explicitly selects installed glslangValidator instead.
 * Top-level stage files and .glsl sources are compiled separately; generic .glsl
 * must declare #pragma shader_stage(...) for glslc, or satisfy glslang's native
 * stage naming rules. Includes follow the compiler's
 * native policy. A fresh output generation prevents failed work from replacing
 * a previous successful result. No GPU, shell, program execution or tool install.
 * Caller trusts source/include paths and the compiler; this is not a sandbox.
 */
;;OVERVIEW
/* MODULE: GLSL native-tool adapter; public records declared in glsl.h.
 * RECORDS: GLSL_ADAPTER and stage selectors share build/run/tools/capabilities.
 * PRIVATE: buildGlsl — source compilation to a fresh generation;
 * rejectRun — shaders cannot be executed as host programs.
 * Output is a caller-owned directory string on success; failure preserves it.
 * Temporary failed generation files are removed; old successful generations stay.
 */

#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

// Compile shader stages without ever treating generated bytecode as a program.
static int buildGlsl(const char *project, char **output) {
    if (project == nullptr || output == nullptr) {
        THROW("invalid GLSL build input");
        return EXIT_FAILURE;
    }
    const char *backend = getenv("GLSL_BACKEND");
    bool glslang = backend != nullptr && strcmp(backend, "glslang") == 0;
    if (backend != nullptr && *backend != '\0' && !glslang && strcmp(backend, "shaderc") != 0) {
        THROW("GLSL_BACKEND must be shaderc or glslang");
        return EXIT_FAILURE;
    }
    size_t count = 0;
    bool ok = false;
    char **sources = Util_collectSources(project, "/*.{vert,frag,comp,geom,tesc,tese,glsl}", &count, &ok);
    if (!ok)
        return EXIT_FAILURE;
    char *base = Util_outputDirectory(project);
    char *directory = base == nullptr ? nullptr : Util_combine(base, "/glsl-XXXXXX");
    free(base);
    if (directory == nullptr || mkdtemp(directory) == nullptr) {
        THROW("cannot create GLSL output generation");
        free(directory);
        Util_freeSources(sources, count);
        return EXIT_FAILURE;
    }
    const char *tool = getenv(glslang ? "GLSLANG_VALIDATOR" : "GLSLC");
    if (tool == nullptr || *tool == '\0')
        tool = glslang ? "glslangValidator" : "glslc";
    int status = 0;
    for (size_t i = 0; i < count && status == 0; ++i) {
        struct stat info;
        if (lstat(sources[i], &info) != 0 || !S_ISREG(info.st_mode)) {
            THROW("GLSL input must be a regular non-symlink file: %s", sources[i]);
            status = EXIT_FAILURE;
            break;
        }
        const char *name = strrchr(sources[i], '/');
        char *stem = Util_combine(directory, name);
        char *artifact = Util_combine(stem, ".spv");
        free(stem);
        char *arguments[] = { (char*) tool, "--target-env=vulkan1.0", "-Werror",
            sources[i], "-o", artifact, nullptr };
        char *fallback[] = { (char*) tool, "-V", "--target-env", "vulkan1.0",
            sources[i], "-o", artifact, nullptr };
        status = Util_executeBuild(glslang ? fallback : arguments);
        if (status == 0 && (stat(artifact, &info) != 0 || !S_ISREG(info.st_mode) || info.st_size == 0)) {
            THROW("GLSL compiler produced no artifact");
            status = EXIT_FAILURE;
        }
        free(artifact);
    }
    if (status == 0)
        *output = directory;
    else {
        for (size_t i = 0; i < count; ++i) {
            char *stem = Util_combine(directory, strrchr(sources[i], '/'));
            char *artifact = Util_combine(stem, ".spv");
            unlink(artifact);
            free(artifact);
            free(stem);
        }
        rmdir(directory);
        free(directory);
    }
    Util_freeSources(sources, count);
    return status;
}

// Shader execution belongs to a graphics pipeline, never the CLI run seam.
static int rejectRun(const char *file, int argc, char **argv, bool buildArtifact) {
    (void) file; (void) argc; (void) argv; (void) buildArtifact;
    THROW("GLSL is build-only; use b build glsl <directory>");
    return EXIT_FAILURE;
}

#define GLSL_RECORD(name, suffix) { name, suffix, buildGlsl, rejectRun, "GLSLC=glslc", "Vulkan SPIR-V build; no host run" }
const Adapter GLSL_ADAPTER = GLSL_RECORD("glsl", ".glsl");
const Adapter GLSL_VERT_ADAPTER = GLSL_RECORD("glsl-vert", ".vert");
const Adapter GLSL_FRAG_ADAPTER = GLSL_RECORD("glsl-frag", ".frag");
const Adapter GLSL_COMP_ADAPTER = GLSL_RECORD("glsl-comp", ".comp");
const Adapter GLSL_GEOM_ADAPTER = GLSL_RECORD("glsl-geom", ".geom");
const Adapter GLSL_TESC_ADAPTER = GLSL_RECORD("glsl-tesc", ".tesc");
const Adapter GLSL_TESE_ADAPTER = GLSL_RECORD("glsl-tese", ".tese");
